int R_EN_L1 = 20;
int L_EN_L1 = 21;
int R_EN_L2 = 22;
int L_EN_L2 = 23;
int R_EN_R1 = 24;
int L_EN_R1 = 25;
int R_EN_R2 = 26;
int L_EN_R2 = 27;
int RPWM_L1 = 2;
int LPWM_L1 = 3;
int RPWM_L2 = 4;
int LPWM_L2 = 5;
int RPWM_R1 = 6;
int LPWM_R1 = 7;
int RPWM_R2 = 8;
int LPWM_R2 = 9;
int TocDoXoay = 255;
int LSpeed = 140;
int RSpeed =140;

void khoiTao(){
  pinMode(R_EN_L1, OUTPUT);
  pinMode(L_EN_L1, OUTPUT);
  pinMode(R_EN_L2, OUTPUT);
  pinMode(L_EN_L2, OUTPUT);
  pinMode(R_EN_R1, OUTPUT);
  pinMode(L_EN_R1, OUTPUT);
  pinMode(R_EN_R2, OUTPUT);
  pinMode(L_EN_R2, OUTPUT);
  pinMode(RPWM_L1, OUTPUT);
  pinMode(LPWM_L1, OUTPUT);
  pinMode(RPWM_L2, OUTPUT);
  pinMode(LPWM_L2, OUTPUT);
  pinMode(RPWM_R1, OUTPUT);
  pinMode(LPWM_R1, OUTPUT);
  pinMode(RPWM_R2, OUTPUT);
  pinMode(LPWM_R2, OUTPUT);
  digitalWrite(R_EN_L1, HIGH);
  digitalWrite(L_EN_L1, HIGH);
  digitalWrite(R_EN_L2, HIGH);
  digitalWrite(L_EN_L2, HIGH);
  digitalWrite(R_EN_R1, HIGH);
  digitalWrite(L_EN_R1, HIGH);
  digitalWrite(R_EN_R2, HIGH);
  digitalWrite(L_EN_R2, HIGH);
}
